version: "3"

services:
  api:
    build: .
    # env_file: ./slack/.env
    ports:
      - "3001:3001"
    volumes:
      - ./:/app
    environment:
      MG_API_KEY: "${MAILGUN_API_KEY}"
      REDIS_URL: "redis://cache"
      UI_PASSWORD: ${UI_PASSWORD}
    depends_on:
      - redis
  redis:
    image: redis
    container_name: cache
    ports:
      - "6379:6379"
    expose:
      - 6379
