version: "3"

services:
  api:
    build: .
    command: bash -c "npm build && npm run dev"
    # env_file: ./slack/.env
    ports:
      - "3001:3001"
    volumes:
      - ./:/app
    environment:
      # Sam's laptop
      # DATABASE_URL: postgres://statustician:statustician@0.tcp.ngrok.io:11433/statustician
      # --
      # Local
      DB_URL: mongodb://mongo:27017
      DB_USER: kwakanalia
      DB_PASSWORD: elycheea
      MG_API_KEY: "${MAILGUN_API_KEY}"
    depends_on:
      - mongo
      - redis
  mongo:
    image: mongo
    environment:
      - MONGO_INITDB_DATABASE=kwakanalia
      - MONGO_INITDB_ROOT_USERNAME=kwakanalia
      - MONGO_INITDB_ROOT_PASSWORD=elycheea
    ports:
      - "27017-27019:27017-27019"
  redis:
    image: redis
    container_name: cache
    ports:
      - "6379:6379"
    expose:
      - 6379
