version: "3"

services:
  api:
    command: bash -c "npm build && npm run start"
    environment:
      NODE_ENV: prod
      MONGO_URL: ${PROD_MONGO_URL}
      MONGO_USER: ${PROD_MONGO_USER}
      MONGO_PASSWORD: ${PROD_MONGO_PASSWORD}
